### ISSUE TITLE
codecov update from 2.1.12 to 2.1.13

### ISSUE THREAD

**Issue by FabianScharnboeck** [se2p/FlaPy#17]
### Codecov 2.1.12 not on pypi index anymore
https://about.codecov.io/blog/message-regarding-the-pypi-package/

_"EDIT 2023-04-17: We have re-instated the codecov package to PyPI as version 2.1.13. We are unfortunately unable to push 2.1.12, and users who still wish to use this package are encouraged to upgrade. We will continue to develop a deprecation plan for this uploader and will announce plans in the upcoming weeks.
On April 12, 2023, Codecov removed the codecov package from PyPI. Our intent was to remove a deprecated, rarely-used package from active support."_

#### The message:
  • Installing codecov (2.1.12): Failed

  RuntimeError

  Unable to find installation candidates for codecov (2.1.12)

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chooser.py:109 in choose_for
      105│ 
      106│             links.append(link)
      107│ 
      108│         if not links:
    → 109│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      110│ 
      111│         # Get the best link
      112│         chosen = max(links, key=lambda link: self._sort_key(package, link))

**I suggest updating codecov to 2.1.13**

**Comment by gruberma** [comment]
Thanks! Fixed via 6cd1c71
