### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by markusobermaier96** [se2p/FlaPy#4]
Numpy threw some errors on my machine, i needed to update it to v '^1.23.3'.
Also, sklearn is deprecated and I replaced it with scikit-learn v '^1.1.2'.
Scipy threw errors caused by missing blas and lapak, so i added scipy v ^1.9.1 to poetry, which fixed it.
Scipy then conflicted with the Python version, so I adjusted Python in pyproject.toml to '>=3.8,<3.12'

**Comment by gruberma** [comment]
Hi Markus, sry for the very late reply, my notifications were not set up properly.

Thanks for pointing out this issue.
Unfortunately, I couldn't reproduce the initial issue with numpy, however, I wanted to update the dependencies anyway cause dependabot keeps asking about it.
I just did so and it upgraded to numpy `1.23.4`, just like you suggested.

I also removed `sklearn`, I don't know why it was in there in the first place, I don't use it.

Could you please check, if you can build the project properly now?

**Comment by markusobermaier96** [comment]
I just downloaded the new flapy version and everything works smoothly! 👍🏼 Thanks
